import { access, readFile } from "node:fs/promises";

const requiredFiles = [
  "index.html",
  "LICENSE",
  "package.json",
  "server.mjs",
  "src/app.js",
  "src/intent-v1.mjs",
  "src/pczt-inspect-v1.mjs",
  "src/pczt-bind-v1.mjs",
  "src/proof-event-v1.mjs",
  "src/fixed-runner-v1.mjs",
  "src/signer-selection-v1.mjs",
  "src/signing-context-v1.mjs",
  "src/signer-review-v1.mjs",
  "src/frost-session-v1.mjs",
  "src/pczt-completion-v1.mjs",
  "src/zecsafe-proof-v1.mjs",
  "src/proof-run-v1.mjs",
  "src/styles.css",
  "README.md",
  "SUBMISSION.md",
  "docs/architecture.md",
  "docs/architecture-diagram.md",
  "docs/demo-script.md",
  "docs/frost-integration.md",
  "docs/frost-windows-setup.md",
  "docs/mainnet-integration.md",
  "docs/mainnet-readonly.md",
  "docs/operator-notepad.md",
  "docs/pr-checklist.md",
  "docs/submission-plan.md",
  "docs/threat-model.md",
  "docs/roadmap.md",
  "docs/screenshots/vault-dashboard.png",
  "docs/screenshots/mainnet-monitor.png",
  "docs/screenshots/transaction-proof.png",
  "docs/screenshots/recovery-flow.png",
  "scripts/frost-local-wrapper.mjs",
  "scripts/create-intent.mjs",
  "scripts/intent-v1.test.mjs",
  "scripts/pczt-inspect.mjs",
  "scripts/pczt-inspect-v1.test.mjs",
  "scripts/pczt-bind.mjs",
  "scripts/pczt-bind-v1.test.mjs",
  "scripts/proof-event.mjs",
  "scripts/proof-event-v1.test.mjs",
  "scripts/fixed-runner.mjs",
  "scripts/fixed-runner-v1.test.mjs",
  "scripts/signer-selection.mjs",
  "scripts/signer-selection-v1.test.mjs",
  "scripts/signing-context-v1.test.mjs",
  "scripts/signer-review.mjs",
  "scripts/signer-review-v1.test.mjs",
  "scripts/frost-session.mjs",
  "scripts/frost-session-v1.test.mjs",
  "scripts/pczt-complete.mjs",
  "scripts/pczt-completion-v1.test.mjs",
  "scripts/zecsafe.mjs",
  "scripts/zecsafe-proof-v1.test.mjs",
  "scripts/proof-run-v1.test.mjs",
  "scripts/capture-screenshots.mjs",
  "docs/proof/zecsafe-proof-v1.schema.json",
  "docs/proof/TRUST_MODEL.md",
  "fixtures/proof-runs/p0-016-dry-broadcast-proof-run.json",
  "fixtures/mainnet-demo/p0-017-mainnet-demo-env.json",
  "PROOF_SPEC.md",
];

for (const file of requiredFiles) {
  await access(file);
}

const html = await readFile("index.html", "utf8");
const app = await readFile("src/app.js", "utf8");
const styles = await readFile("src/styles.css", "utf8");

const checks = [
  [html.includes('<div id="app"></div>'), "index.html mounts #app"],
  [html.includes('type="module" src="src/app.js"'), "index.html loads app module"],
  [app.includes("function render()"), "app.js includes render flow"],
  [app.includes("setGuardianStatus"), "app.js includes guardian approval logic"],
  [app.includes("lookupTransparentAddress"), "app.js includes mainnet lookup logic"],
  [app.includes("syncViewingKeyBalance"), "app.js includes viewing key sync logic"],
  [app.includes("checkTransactionProof"), "app.js includes transaction proof logic"],
  [app.includes("FROST Live Demo"), "app.js includes FROST explanation"],
  [app.includes("Security boundaries"), "app.js includes visible threat model"],
  [app.includes("navGroups") && app.includes("Vault Overview") && app.includes("Proposal Center") && app.includes("Guardian Center") && app.includes("FROST Live Demo"), "app.js includes grouped navigation labels"],
  [app.includes("enableStandardTrackpadScroll"), "app.js includes standard trackpad scrolling"],
  [app.includes("Mainnet check successful"), "app.js includes strong mainnet success card"],
  [app.includes("Zcash mainnet infrastructure connected"), "app.js includes chain status card"],
  [app.includes("checkMainnetStatus"), "app.js includes mainnet status check"],
  [app.includes("renderLiveMainnetPanel"), "app.js includes live mainnet dashboard panel"],
  [app.includes("runFrostDemo"), "app.js includes FROST demo runner"],
  [app.includes("canonicalProposalPayload") && app.includes("proposalPayloadHash"), "app.js binds FROST proof to proposal payload hash"],
  [app.includes("signGuardianApproval") && app.includes("guardianSignatureProofsFor"), "app.js includes browser-side guardian signature proofs"],
  [app.includes("Controlled Mainnet Proof") && app.includes("proposalMainnetProofs"), "app.js includes proposal-specific controlled mainnet proof mode"],
  [app.includes("downloadProofBundle"), "app.js includes downloadable proof bundle export"],
  [!app.includes("Start Judge Walkthrough") && !app.includes("renderJudgeMode"), "app.js keeps operator walkthrough out of main product UI"],
  [app.includes("Generate Proof Bundle"), "app.js includes proof bundle UI"],
  [app.includes("audit-badge"), "app.js includes audit badges"],
  [app.includes("Transaction proof found on Zcash mainnet"), "app.js includes strong tx proof card"],
  [app.includes("renderRecoveryResult"), "app.js includes interactive recovery workflow"],
  [app.includes("Recovery Risk: High"), "app.js includes high-risk recovery warning"],
  [app.includes("RECOVERY_NEW_VAULT_FINGERPRINT"), "app.js includes recovery fingerprint"],
  [app.includes("flagRecoverySuspicious"), "app.js includes suspicious recovery flag"],
  [app.includes("Recovery timelock started"), "app.js includes recovery timelock"],
  [app.includes("How ZecSafe works"), "app.js includes in-app architecture flow"],
  [(await readFile("docs/operator-notepad.md", "utf8")).includes("ZecSafe Operator Notepad"), "operator notepad exists outside main app UI"],
  [styles.includes("position: fixed"), "styles.css keeps desktop navigation fixed"],
  [(await readFile("server.mjs", "utf8")).includes("/api/mainnet/status"), "server includes mainnet status route"],
  [(await readFile("server.mjs", "utf8")).includes("/api/mainnet-status"), "server includes combined mainnet status route"],
  [(await readFile("server.mjs", "utf8")).includes("/api/mainnet/address-balance"), "server includes address balance route"],
  [(await readFile("server.mjs", "utf8")).includes("/api/frost-demo"), "server includes FROST demo route"],
  [(await readFile("server.mjs", "utf8")).includes("/api/proof-bundle"), "server includes proof bundle route"],
  [(await readFile("server.mjs", "utf8")).includes("/api/intent/create"), "server includes deterministic intent route"],
  [(await readFile("src/intent-v1.mjs", "utf8")).includes("zecsafe-intent-v1"), "intent module defines schema version"],
  [(await readFile("scripts/create-intent.mjs", "utf8")).includes("Intent commitment:"), "intent CLI emits commitment"],
  [(await readFile("scripts/intent-v1.test.mjs", "utf8")).includes("scientific notation"), "intent tests cover scientific notation rejection"],
  [(await readFile("src/pczt-inspect-v1.mjs", "utf8")).includes("EXPECTED_ZCASH_DEVTOOL_COMMIT"), "PCZT inspect module pins zcash-devtool commit"],
  [(await readFile("src/pczt-inspect-v1.mjs", "utf8")).includes("parseIronwoodReview"), "PCZT inspect module parses Ironwood inspect output"],
  [(await readFile("scripts/pczt-inspect.mjs", "utf8")).includes("PCZT inspect review created"), "PCZT inspect CLI emits structured review"],
  [(await readFile("scripts/pczt-inspect-v1.test.mjs", "utf8")).includes("unexpected extra inspect output"), "PCZT inspect tests cover strict output rejection"],
  [(await readFile("scripts/pczt-inspect-v1.test.mjs", "utf8")).includes("validIronwoodInspect"), "PCZT inspect tests cover Ironwood V6 output"],
  [(await readFile("src/pczt-bind-v1.mjs", "utf8")).includes("zecsafe-binding-report-v1"), "Binding Firewall module defines report schema version"],
  [(await readFile("src/pczt-bind-v1.mjs", "utf8")).includes("unreported-change-output"), "Binding Firewall models unreported change recipients"],
  [(await readFile("scripts/pczt-bind.mjs", "utf8")).includes("INTENT ↔ PCZT"), "Binding Firewall CLI emits summary proof lines"],
  [(await readFile("scripts/pczt-bind-v1.test.mjs", "utf8")).includes("FROST SESSION: BLOCKED"), "Binding Firewall tests cover blocked signing summary"],
  [(await readFile("src/proof-event-v1.mjs", "utf8")).includes("proof-event-v1"), "ProofEvent module defines schema version"],
  [(await readFile("src/proof-event-v1.mjs", "utf8")).includes("reduceProofEvents"), "ProofEvent module includes reducer"],
  [(await readFile("scripts/proof-event.mjs", "utf8")).includes("replay"), "ProofEvent CLI includes replay command"],
  [(await readFile("scripts/proof-event-v1.test.mjs", "utf8")).includes("unsupported public data field: recipient"), "ProofEvent tests reject private recipient field"],
  [(await readFile("src/fixed-runner-v1.mjs", "utf8")).includes("FIXED_OPERATIONS"), "Fixed runner module defines operation allowlist"],
  [(await readFile("src/fixed-runner-v1.mjs", "utf8")).includes("shell: false"), "Fixed runner uses shell:false"],
  [(await readFile("scripts/fixed-runner.mjs", "utf8")).includes("Fixed runner rejected"), "Fixed runner CLI emits controlled rejection"],
  [(await readFile("scripts/fixed-runner-v1.test.mjs", "utf8")).includes("spawn should not run for rejected path payloads"), "Fixed runner tests reject path payloads before spawn"],
  [(await readFile("src/signer-selection-v1.mjs", "utf8")).includes("zecsafe-signer-selection-v1"), "Signer selection module defines schema version"],
  [(await readFile("src/signer-selection-v1.mjs", "utf8")).includes("selected_public_fingerprints"), "Signer selection module emits public selected fingerprints"],
  [(await readFile("scripts/signer-selection.mjs", "utf8")).includes("THRESHOLD:"), "Signer selection CLI emits threshold summary"],
  [(await readFile("scripts/signer-selection-v1.test.mjs", "utf8")).includes("SIGNER SELECTION: BLOCKED"), "Signer selection tests cover blocked summary"],
  [(await readFile("scripts/fixed-runner-v1.test.mjs", "utf8")).includes("frost.session.status"), "Fixed runner tests cover signer selection operation"],
  [(await readFile("src/signing-context-v1.mjs", "utf8")).includes("zecsafe-signing-context-v1"), "Signing context module defines schema version"],
  [(await readFile("scripts/signing-context-v1.test.mjs", "utf8")).includes("signing_context_expired"), "Signing context tests cover expiry"],
  [(await readFile("src/fixed-runner-v1.mjs", "utf8")).includes('"signing.prepare": operationSigningPrepare'), "Fixed runner implements signing preparation"],
  [(await readFile("src/signer-review-v1.mjs", "utf8")).includes("zecsafe-signer-review-v1"), "Signer review module defines schema version"],
  [(await readFile("scripts/signer-review.mjs", "utf8")).includes("SIGNER REVIEW:"), "Signer review CLI emits summary proof lines"],
  [(await readFile("scripts/signer-review-v1.test.mjs", "utf8")).includes("independently rerun SIGHASH"), "Signer review tests cover honest review-mode limitation"],
  [(await readFile("src/fixed-runner-v1.mjs", "utf8")).includes('"signer.review": operationSignerReview'), "Fixed runner implements signer review"],
  [(await readFile("src/frost-session-v1.mjs", "utf8")).includes("zecsafe-frost-session-v1"), "FROST session module defines schema version"],
  [(await readFile("scripts/frost-session.mjs", "utf8")).includes("THRESHOLD:"), "FROST session CLI emits threshold summary"],
  [(await readFile("scripts/frost-session-v1.test.mjs", "utf8")).includes("FROST SESSION: NOT_STARTED"), "FROST session tests cover one-signer negative proof"],
  [(await readFile("src/fixed-runner-v1.mjs", "utf8")).includes('"frost.session.start": operationFrostSessionStart'), "Fixed runner implements FROST session start"],
  [(await readFile("src/pczt-completion-v1.mjs", "utf8")).includes("zecsafe-pczt-completion-v1"), "PCZT completion module defines schema version"],
  [(await readFile("scripts/pczt-complete.mjs", "utf8")).includes("SIGNED_PCZT"), "PCZT completion CLI emits signed PCZT summary"],
  [(await readFile("scripts/pczt-completion-v1.test.mjs", "utf8")).includes("mock_signature"), "PCZT completion tests reject mock signatures"],
  [(await readFile("src/fixed-runner-v1.mjs", "utf8")).includes('"pczt.combine": operationPcztCompletion'), "Fixed runner implements PCZT completion"],
  [(await readFile("src/zecsafe-proof-v1.mjs", "utf8")).includes("zecsafe-proof-v1"), "Proof v1 module defines schema version"],
  [(await readFile("src/proof-run-v1.mjs", "utf8")).includes("zecsafe-proof-run-v1"), "Proof-run module defines schema version"],
  [(await readFile("scripts/zecsafe.mjs", "utf8")).includes("proof generate"), "ZecSafe CLI supports proof generation"],
  [(await readFile("scripts/zecsafe.mjs", "utf8")).includes("proof-run --dry-broadcast"), "ZecSafe CLI supports dry proof run"],
  [(await readFile("scripts/zecsafe-proof-v1.test.mjs", "utf8")).includes("selected_signer"), "Proof v1 tests cover selected signer tampering"],
  [(await readFile("scripts/proof-run-v1.test.mjs", "utf8")).includes("Mainnet broadcast requires human approval"), "Proof-run tests cover broadcast approval wait"],
  [(await readFile("fixtures/proof-runs/p0-016-dry-broadcast-proof-run.json", "utf8")).includes('"mode": "dry-broadcast"'), "Dry proof-run fixture exists"],
  [(await readFile("fixtures/mainnet-demo/p0-017-mainnet-demo-env.json", "utf8")).includes('"schema_version": "zecsafe-mainnet-demo-env-v1"'), "Mainnet demo env fixture exists"],
  [(await readFile("fixtures/mainnet-demo/p0-017-mainnet-demo-env.json", "utf8")).includes('"network": "main"'), "Mainnet demo env fixture records main network"],
  [(await readFile("fixtures/mainnet-demo/p0-017-mainnet-demo-env.json", "utf8")).includes('"funding_status": "NOT_FUNDED"'), "Mainnet demo env fixture records funding boundary"],
  [!(await readFile("fixtures/mainnet-demo/p0-017-mainnet-demo-env.json", "utf8")).match(/uview|secret-extended-key|-----BEGIN|zffrost1|contact-token/i), "Mainnet demo env fixture excludes private material values"],
  [(await readFile("src/fixed-runner-v1.mjs", "utf8")).includes('"proof.generate": operationProofGenerate'), "Fixed runner implements proof generation"],
  [(await readFile("src/fixed-runner-v1.mjs", "utf8")).includes('"proof.verify": operationProofVerify'), "Fixed runner implements proof verification"],
  [(await readFile("docs/proof/zecsafe-proof-v1.schema.json", "utf8")).includes('"zecsafe-proof-v1"'), "Proof JSON schema exists"],
  [(await readFile("PROOF_SPEC.md", "utf8")).includes("bundle_hash"), "Proof spec documents bundle hash"],
  [(await readFile("scripts/frost-demo.mjs", "utf8")).includes("frost-local-wrapper.mjs"), "FROST demo runs built-in local wrapper"],
  [(await readFile("scripts/frost-local-wrapper.mjs", "utf8")).includes("trusted-dealer"), "FROST wrapper uses trusted-dealer"],
  [(await readFile("scripts/frost-local-wrapper.mjs", "utf8")).includes("coordinator"), "FROST wrapper uses coordinator"],
  [(await readFile("scripts/frost-local-wrapper.mjs", "utf8")).includes("participant"), "FROST wrapper uses participants"],
  [(await readFile("server.mjs", "utf8")).includes("getmempoolinfo"), "server includes mempool status call"],
  [(await readFile("README.md", "utf8")).includes("How It Uses Zcash Mainnet"), "README includes mainnet usage"],
  [(await readFile("README.md", "utf8")).includes("Real vs Simulated"), "README includes real vs simulated table"],
  [(await readFile("README.md", "utf8")).includes("Guardian approval acknowledgement"), "README documents guardian signature acknowledgements"],
  [(await readFile("README.md", "utf8")).includes("Controlled Mainnet Proof Workflow"), "README documents controlled mainnet proof workflow"],
  [(await readFile("README.md", "utf8")).includes("FROST Library"), "README includes FROST library section"],
  [(await readFile("README.md", "utf8")).includes("docs/threat-model.md"), "README links threat model"],
  [(await readFile("docs/frost-integration.md", "utf8")).includes("frost-local-wrapper.mjs"), "FROST docs include built-in wrapper"],
  [(await readFile("docs/frost-windows-setup.md", "utf8")).includes("Visual Studio C++ Build Tools"), "FROST Windows setup includes MSVC requirement"],
  [(await readFile("docs/mainnet-integration.md", "utf8")).includes("getpeerinfo"), "mainnet docs include peer status call"],
  [(await readFile("SUBMISSION.md", "utf8")).includes("ZecHub Hackathon 2026 Submission"), "submission file exists"],
  [(await readFile("docs/architecture-diagram.md", "utf8")).includes("flowchart TD"), "architecture diagram includes Mermaid"],
  [(await readFile("docs/demo-script.md", "utf8")).includes("Target length"), "demo script exists"],
  [(await readFile("docs/threat-model.md", "utf8")).includes("Sensitive Data Rules"), "threat model includes sensitive data rules"],
  [styles.includes("@media (max-width: 680px)"), "styles.css includes mobile breakpoint"],
];

const failures = checks.filter(([passed]) => !passed);

if (failures.length > 0) {
  for (const [, message] of failures) {
    console.error(`Missing check: ${message}`);
  }
  process.exit(1);
}

console.log("ZecSafe static verification passed.");
