import { createHash } from "node:crypto";
import { access, readFile } from "node:fs/promises";

const P0_018_COMPAT_PATCH_REF = "sha256:4a44cfc533dec72fb4e93bcbf81406260d4b3f6e77344b53035426ab297c7d8e";

const requiredFiles = [
  "index.html",
  "LICENSE",
  "package.json",
  "server.mjs",
  "vercel.json",
  "src/app.js",
  "src/intent-v1.mjs",
  "src/pczt-inspect-v1.mjs",
  "src/pczt-bind-v1.mjs",
  "src/proof-event-v1.mjs",
  "src/demo-proof-state.mjs",
  "src/demo-presentation.mjs",
  "src/fixed-runner-v1.mjs",
  "src/signer-selection-v1.mjs",
  "src/signing-context-v1.mjs",
  "src/signer-review-v1.mjs",
  "src/frost-session-v1.mjs",
  "src/pczt-completion-v1.mjs",
  "src/zecsafe-proof-v1.mjs",
  "src/proof-run-v1.mjs",
  "src/mainnet-view-v1.mjs",
  "src/styles.css",
  "README.md",
  "SUBMISSION.md",
  "DEMO.md",
  "SECURITY.md",
  "PRIVACY.md",
  "docs/architecture.md",
  "docs/architecture-diagram.md",
  "docs/demo-script.md",
  "docs/frost-integration.md",
  "docs/frost-windows-setup.md",
  "docs/mainnet-integration.md",
  "docs/mainnet-readonly.md",
  "docs/pr-checklist.md",
  "docs/submission-plan.md",
  "docs/threat-model.md",
  "docs/claim-to-code-matrix.md",
  "docs/submission-gate.md",
  "docs/README.md",
  "docs/history/README.md",
  "docs/history/audit/21-FINAL-AUDIT-REPORT.md",
  "docs/history/execution/30-VERIFIED-MAINNET-RUN.md",
  "docs/screenshots/01-first-glance.png",
  "docs/screenshots/03-binding-firewall.png",
  "docs/screenshots/04-binding-mismatch.png",
  "docs/screenshots/05-authorize-unavailable.png",
  "docs/screenshots/06-proof-detail.png",
  "docs/screenshots/07-mobile-390.png",
  "scripts/frost-local-wrapper.mjs",
  "scripts/build-vercel.mjs",
  "scripts/create-intent.mjs",
  "scripts/intent-v1.test.mjs",
  "scripts/pczt-inspect.mjs",
  "scripts/pczt-inspect-v1.test.mjs",
  "scripts/pczt-bind.mjs",
  "scripts/pczt-bind-v1.test.mjs",
  "scripts/proof-event.mjs",
  "scripts/proof-event-v1.test.mjs",
  "scripts/demo-proof-state.test.mjs",
  "scripts/demo-presentation.test.mjs",
  "scripts/proof-data-classification.test.mjs",
  "scripts/fixed-runner.mjs",
  "scripts/fixed-runner-v1.test.mjs",
  "scripts/signer-selection.mjs",
  "scripts/signer-selection-v1.test.mjs",
  "scripts/signing-context-v1.test.mjs",
  "scripts/signer-review.mjs",
  "scripts/signer-review-v1.test.mjs",
  "scripts/frost-session.mjs",
  "scripts/frost-session-v1.test.mjs",
  "scripts/pczt-complete.mjs",
  "scripts/pczt-completion-v1.test.mjs",
  "scripts/zecsafe.mjs",
  "scripts/zecsafe-proof-v1.test.mjs",
  "scripts/proof-run-v1.test.mjs",
  "scripts/mainnet-view.mjs",
  "scripts/mainnet-view-v1.test.mjs",
  "scripts/capture-screenshots.mjs",
  "docs/proof/zecsafe-proof-v1.schema.json",
  "docs/proof/TRUST_MODEL.md",
  "fixtures/proof-runs/p0-016-dry-broadcast-proof-run.json",
  "fixtures/mainnet-demo/p0-017-mainnet-demo-env.json",
  "fixtures/mainnet-demo/p0-018-view-only-preflight-pending.json",
  "fixtures/mainnet-demo/p0-018-view-only-preflight-funded.json",
  "patches/zcash-devtool/p0-018-pre-ironwood-subtree-compat.patch",
  "PROOF_SPEC.md",
];

async function exists(path) {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

for (const file of requiredFiles) {
  await access(file);
}

const html = await readFile("index.html", "utf8");
const app = await readFile("src/app.js", "utf8");
const styles = await readFile("src/styles.css", "utf8");
const server = await readFile("server.mjs", "utf8");
const vercelConfig = JSON.parse(await readFile("vercel.json", "utf8"));
const vercelBuild = await readFile("scripts/build-vercel.mjs", "utf8");
const readme = await readFile("README.md", "utf8");
const VERIFIED_PROOF_PATH = "fixtures/verified-mainnet-run/proof.json";
const VERIFIED_EVENTS_PATH = "fixtures/verified-mainnet-run/events.public.json";
const p0_018CompatPatch = await readFile("patches/zcash-devtool/p0-018-pre-ironwood-subtree-compat.patch");
const p0_018CompatPatchRef = `sha256:${createHash("sha256").update(p0_018CompatPatch).digest("hex")}`;

const checks = [
  [html.includes('<div id="app"></div>'), "index.html mounts #app"],
  [html.includes('type="module" src="src/app.js"'), "index.html loads app module"],
  [app.includes("function render()"), "app.js includes render flow"],
  [app.includes("Lose one key, not your ZEC."), "app.js includes proof-first demo headline"],
  [app.includes("SAFETY TEST &mdash; NOT A BROADCAST TRANSACTION"), "app.js includes Binding Firewall mismatch safety label"],
  [app.includes("Proof Download Disabled in Safety Test"), "app.js disables proof export in synthetic mismatch mode"],
  [(await readFile("src/demo-presentation.mjs", "utf8")).includes("NOT STARTED — BLOCKED BY BINDING FIREWALL"), "demo presentation keeps later FROST outcomes out of the synthetic mismatch path"],
  [app.includes("Zcash validates the resulting spend authorization normally."), "app.js includes FROST provenance chain note"],
  [app.includes("semantic_pczt_review"), "app.js discloses the real signer review mode"],
  [app.includes("reduceDemoProofEvents"), "app.js derives run state from recorded ProofEvents"],
  [app.includes(VERIFIED_PROOF_PATH) && app.includes(VERIFIED_EVENTS_PATH), "app.js loads the tracked verified mainnet fixtures"],
  [app.includes("make judge-proof-mainnet"), "app.js points judges at the one-command verifier"],
  [app.includes("did not include rerandomized FROST"), "app.js discloses the rerandomized FROST audit scope"],
  [app.includes("Recovery is not demonstrated."), "app.js does not claim recovery"],

  // Four human steps, four primary navigation items.
  [["#review", "#verify", "#authorize", "#prove"].every((hash) => app.includes(hash)), "app.js implements the four-step Review/Verify/Authorize/Prove flow"],
  [(app.match(/href: "#/g) ?? []).length <= 4, "app.js keeps primary navigation to at most four items"],

  // Stale-surface demolition proof. These MUST stay deleted.
  [!app.includes("guardian") && !app.includes("Guardian"), "app.js contains no browser guardian approval surface"],
  [!app.includes("FROST Live Demo"), "app.js does not present a proposal-hash signature as FROST"],
  [!app.includes("Recovery Center") && !app.includes("RECOVERY_NEW_VAULT_FINGERPRINT"), "app.js does not present simulated recovery"],
  [!app.includes("Proposal Center") && !app.includes("Evidence Center") && !app.includes("Vault Policy"), "app.js does not expose legacy prototype routes"],
  [!app.includes("Not Yet Run") && !app.includes("Disabled in Prototype"), "app.js does not contradict the verified mainnet run"],
  [!app.includes("b138c395") && !app.includes("t3Vz22vK"), "app.js contains no default sample txid or address"],
  [!server.includes("/api/proof-bundle"), "server no longer exposes the legacy proof-bundle route"],
  [!server.includes("/api/frost-demo"), "server no longer exposes the proposal-hash FROST demo route"],
  [!server.includes("/api/viewing-key-balance"), "server no longer accepts a viewing key over HTTP"],
  [!server.includes("/api/mainnet/address-balance"), "server no longer exposes the transparent address monitor"],
  [!server.includes("b138c395") && !server.includes("t3Vz22vK"), "server contains no default sample txid or address"],

  // Retained server surface.
  [server.includes("/api/mainnet/status"), "server includes mainnet status route"],
  [server.includes("/api/transaction-proof"), "server includes chain-observation transaction route"],
  [server.includes("/api/intent/create"), "server includes deterministic intent route"],
  [server.includes("/api/health"), "server includes health route"],

  // R-08 hardening. These must not regress.
  [server.includes('server.listen(port, host'), "server binds an explicit host"],
  [server.includes('process.env.ZECSAFE_HOST ?? "127.0.0.1"'), "server defaults to loopback, not all interfaces"],
  [server.includes("STATIC_PREFIXES") && !server.includes("return join(rootDir, normalized);\n}"), "server serves an explicit static allowlist, not the repository root"],
  [server.includes("Content-Security-Policy"), "server sets a Content-Security-Policy"],
  [server.includes("X-Content-Type-Options"), "server sets X-Content-Type-Options"],

  // Public hosting is a static allowlisted artifact, not the local repository server.
  [vercelConfig.framework === null, "Vercel uses the framework-neutral static preset"],
  [vercelConfig.outputDirectory === "dist", "Vercel serves only the generated dist directory"],
  [vercelConfig.rewrites?.some((route) => route.source === "/demo" && route.destination === "/index.html"), "Vercel routes /demo to the static proof app"],
  [vercelConfig.headers?.some((route) => route.headers?.some((header) => header.key === "Content-Security-Policy")), "Vercel applies a Content-Security-Policy"],
  [vercelBuild.includes("publicFiles") && vercelBuild.includes("Unexpected Vercel output"), "Vercel build enforces an exact public-file allowlist"],
  [!vercelBuild.includes("server.mjs") && !vercelBuild.includes("docs/audit"), "Vercel output excludes the local server and audit corpus"],

  [(await readFile("src/intent-v1.mjs", "utf8")).includes("zecsafe-intent-v1"), "intent module defines schema version"],
  [(await readFile("scripts/create-intent.mjs", "utf8")).includes("Intent commitment:"), "intent CLI emits commitment"],
  [(await readFile("scripts/intent-v1.test.mjs", "utf8")).includes("scientific notation"), "intent tests cover scientific notation rejection"],
  [(await readFile("src/pczt-inspect-v1.mjs", "utf8")).includes("EXPECTED_ZCASH_DEVTOOL_COMMIT"), "PCZT inspect module pins zcash-devtool commit"],
  [(await readFile("src/pczt-inspect-v1.mjs", "utf8")).includes("parseShieldedReview"), "PCZT inspect module parses shielded action inspect output"],
  [(await readFile("src/pczt-inspect-v1.mjs", "utf8")).includes("Ironwood: \"ironwood\""), "PCZT inspect module supports Ironwood actions"],
  [(await readFile("src/pczt-inspect-v1.mjs", "utf8")).includes("Orchard: \"orchard\""), "PCZT inspect module supports Orchard actions"],
  [(await readFile("scripts/pczt-inspect.mjs", "utf8")).includes("PCZT inspect review created"), "PCZT inspect CLI emits structured review"],
  [(await readFile("scripts/pczt-inspect-v1.test.mjs", "utf8")).includes("unexpected extra inspect output"), "PCZT inspect tests cover strict output rejection"],
  [(await readFile("scripts/pczt-inspect-v1.test.mjs", "utf8")).includes("validIronwoodInspect"), "PCZT inspect tests cover Ironwood V6 output"],
  [(await readFile("scripts/pczt-inspect-v1.test.mjs", "utf8")).includes("validOrchardInspect"), "PCZT inspect tests cover mainnet Orchard V5 output"],
  [(await readFile("src/pczt-bind-v1.mjs", "utf8")).includes("zecsafe-binding-report-v1"), "Binding Firewall module defines report schema version"],
  [(await readFile("src/pczt-bind-v1.mjs", "utf8")).includes("unreported-change-output"), "Binding Firewall models unreported change recipients"],
  [(await readFile("scripts/pczt-bind.mjs", "utf8")).includes("INTENT ↔ PCZT"), "Binding Firewall CLI emits summary proof lines"],
  [(await readFile("scripts/pczt-bind-v1.test.mjs", "utf8")).includes("FROST SESSION: BLOCKED"), "Binding Firewall tests cover blocked signing summary"],
  [(await readFile("src/proof-event-v1.mjs", "utf8")).includes("proof-event-v1"), "ProofEvent module defines schema version"],
  [(await readFile("src/proof-event-v1.mjs", "utf8")).includes("reduceProofEvents"), "ProofEvent module includes reducer"],
  [(await readFile("src/demo-proof-state.mjs", "utf8")).includes("reduceDemoProofEvents"), "W4 demo ProofEvent state reducer exists"],
  [(await readFile("src/demo-presentation.mjs", "utf8")).includes("Synthetic safety-test replays cannot be exported"), "demo presentation rejects synthetic proof exports"],
  [(await readFile("scripts/demo-presentation.test.mjs", "utf8")).includes("FROST NOT STARTED"), "demo presentation tests assert a coherent blocked mismatch state"],
  [(await readFile("SECURITY.md", "utf8")).includes("coordinator is trusted with transaction privacy and unlinkability"), "SECURITY documents coordinator privacy trust"],
  [(await readFile("SECURITY.md", "utf8")).includes("did not include rerandomized FROST"), "SECURITY documents rerandomized FROST audit scope"],
  [(await readFile("PRIVACY.md", "utf8")).includes("classification labels, not the underlying recipient"), "PRIVACY documents public proof field-label exception"],
  [(await readFile("DEMO.md", "utf8")).includes("http://127.0.0.1:4173/demo"), "DEMO documents proof-first route"],
  [(await readFile("docs/claim-to-code-matrix.md", "utf8")).includes("C-010"), "Claim matrix includes production/audit claim guard"],
  [(await readFile("docs/submission-gate.md", "utf8")).includes("NO-GO - P0 BLOCKERS REMAIN"), "Submission gate records current external blockers"],
  [(await readFile("scripts/proof-event.mjs", "utf8")).includes("replay"), "ProofEvent CLI includes replay command"],
  [(await readFile("scripts/proof-event-v1.test.mjs", "utf8")).includes("unsupported public data field: recipient"), "ProofEvent tests reject private recipient field"],
  [(await readFile("src/fixed-runner-v1.mjs", "utf8")).includes("FIXED_OPERATIONS"), "Fixed runner module defines operation allowlist"],
  [(await readFile("src/fixed-runner-v1.mjs", "utf8")).includes("shell: false"), "Fixed runner uses shell:false"],
  [(await readFile("scripts/fixed-runner.mjs", "utf8")).includes("Fixed runner rejected"), "Fixed runner CLI emits controlled rejection"],
  [(await readFile("scripts/fixed-runner-v1.test.mjs", "utf8")).includes("spawn should not run for rejected path payloads"), "Fixed runner tests reject path payloads before spawn"],
  [(await readFile("src/signer-selection-v1.mjs", "utf8")).includes("zecsafe-signer-selection-v1"), "Signer selection module defines schema version"],
  [(await readFile("src/signer-selection-v1.mjs", "utf8")).includes("selected_public_fingerprints"), "Signer selection module emits public selected fingerprints"],
  [(await readFile("scripts/signer-selection.mjs", "utf8")).includes("THRESHOLD:"), "Signer selection CLI emits threshold summary"],
  [(await readFile("scripts/signer-selection-v1.test.mjs", "utf8")).includes("SIGNER SELECTION: BLOCKED"), "Signer selection tests cover blocked summary"],
  [(await readFile("scripts/fixed-runner-v1.test.mjs", "utf8")).includes("frost.session.status"), "Fixed runner tests cover signer selection operation"],
  [(await readFile("src/signing-context-v1.mjs", "utf8")).includes("zecsafe-signing-context-v1"), "Signing context module defines schema version"],
  [(await readFile("scripts/signing-context-v1.test.mjs", "utf8")).includes("signing_context_expired"), "Signing context tests cover expiry"],
  [(await readFile("src/fixed-runner-v1.mjs", "utf8")).includes('"signing.prepare": operationSigningPrepare'), "Fixed runner implements signing preparation"],
  [(await readFile("src/signer-review-v1.mjs", "utf8")).includes("zecsafe-signer-review-v1"), "Signer review module defines schema version"],
  [(await readFile("scripts/signer-review.mjs", "utf8")).includes("SIGNER REVIEW:"), "Signer review CLI emits summary proof lines"],
  [(await readFile("scripts/signer-review-v1.test.mjs", "utf8")).includes("independently rerun SIGHASH"), "Signer review tests cover honest review-mode limitation"],
  [(await readFile("src/fixed-runner-v1.mjs", "utf8")).includes('"signer.review": operationSignerReview'), "Fixed runner implements signer review"],
  [(await readFile("src/frost-session-v1.mjs", "utf8")).includes("zecsafe-frost-session-v1"), "FROST session module defines schema version"],
  [(await readFile("scripts/frost-session.mjs", "utf8")).includes("THRESHOLD:"), "FROST session CLI emits threshold summary"],
  [(await readFile("scripts/frost-session-v1.test.mjs", "utf8")).includes("FROST SESSION: NOT_STARTED"), "FROST session tests cover one-signer negative proof"],
  [(await readFile("src/fixed-runner-v1.mjs", "utf8")).includes('"frost.session.start": operationFrostSessionStart'), "Fixed runner implements FROST session start"],
  [(await readFile("src/pczt-completion-v1.mjs", "utf8")).includes("zecsafe-pczt-completion-v1"), "PCZT completion module defines schema version"],
  [(await readFile("scripts/pczt-complete.mjs", "utf8")).includes("SIGNED_PCZT"), "PCZT completion CLI emits signed PCZT summary"],
  [(await readFile("scripts/pczt-completion-v1.test.mjs", "utf8")).includes("mock_signature"), "PCZT completion tests reject mock signatures"],
  [(await readFile("src/fixed-runner-v1.mjs", "utf8")).includes('"pczt.combine": operationPcztCompletion'), "Fixed runner implements PCZT completion"],
  [(await readFile("src/zecsafe-proof-v1.mjs", "utf8")).includes("zecsafe-proof-v1"), "Proof v1 module defines schema version"],
  [(await readFile("fixtures/verified-mainnet-run/proof.json", "utf8")).includes('"signer_review_mode": "semantic_pczt_review"'), "recorded bundle states the real signer review mode inside the hash boundary"],
  [(await readFile("docs/proof/zecsafe-proof-v1.schema.json", "utf8")).includes("signer_review_mode"), "proof schema requires signer_review_mode"],
  [(await readFile("scripts/zecsafe-proof-v1.test.mjs", "utf8")).includes("REPRODUCIBILITY"), "proof tests guard bundle reproducibility"],
  [(await readFile("src/zecsafe-proof-v1.mjs", "utf8")).includes("occurred_at: recordedAt"), "proof generation pins the completion event time so the bundle is reproducible"],
  [(await readFile("PROOF_SPEC.md", "utf8")).includes("semantic_pczt_review"), "proof spec discloses the signer review mode"],
  [(await readFile("PROOF_SPEC.md", "utf8")).includes("Binding Firewall and the FROST-key linkage"), "proof spec separates the Binding Firewall from the FROST-key linkage"],
  [(await readFile("docs/proof/TRUST_MODEL.md", "utf8")).includes("Binding Firewall vs the FROST-key linkage"), "trust model separates the Binding Firewall from the FROST-key linkage"],
  [(await readFile("SECURITY.md", "utf8")).includes("Binding Firewall is semantic"), "SECURITY separates the Binding Firewall from the FROST-key linkage"],
  [(await readFile("src/proof-run-v1.mjs", "utf8")).includes("zecsafe-proof-run-v1"), "Proof-run module defines schema version"],
  [(await readFile("src/mainnet-view-v1.mjs", "utf8")).includes("zecsafe-mainnet-view-preflight-v1"), "Mainnet view preflight module defines schema version"],
  [(await readFile("scripts/zecsafe.mjs", "utf8")).includes("proof generate"), "ZecSafe CLI supports proof generation"],
  [(await readFile("scripts/zecsafe.mjs", "utf8")).includes("proof-run --dry-broadcast"), "ZecSafe CLI supports dry proof run"],
  [(await readFile("scripts/mainnet-view.mjs", "utf8")).includes("mainnet-view preflight"), "Mainnet view CLI supports preflight"],
  [(await readFile("scripts/mainnet-view.mjs", "utf8")).includes("mainnet-view watch"), "Mainnet view CLI supports watch"],
  [(await readFile("scripts/zecsafe-proof-v1.test.mjs", "utf8")).includes("selected_signer"), "Proof v1 tests cover selected signer tampering"],
  [(await readFile("scripts/proof-run-v1.test.mjs", "utf8")).includes("Mainnet broadcast requires human approval"), "Proof-run tests cover broadcast approval wait"],
  [(await readFile("scripts/mainnet-view-v1.test.mjs", "utf8")).includes("WAIT_FUNDING"), "Mainnet view tests cover funding wait"],
  [(await readFile("fixtures/proof-runs/p0-016-dry-broadcast-proof-run.json", "utf8")).includes('"mode": "dry-broadcast"'), "Dry proof-run fixture exists"],
  [(await readFile("fixtures/mainnet-demo/p0-017-mainnet-demo-env.json", "utf8")).includes('"schema_version": "zecsafe-mainnet-demo-env-v1"'), "Mainnet demo env fixture exists"],
  [(await readFile("fixtures/mainnet-demo/p0-017-mainnet-demo-env.json", "utf8")).includes('"network": "main"'), "Mainnet demo env fixture records main network"],
  [(await readFile("fixtures/mainnet-demo/p0-017-mainnet-demo-env.json", "utf8")).includes('"funding_status": "NOT_FUNDED"'), "Mainnet demo env fixture records funding boundary"],
  [!(await readFile("fixtures/mainnet-demo/p0-017-mainnet-demo-env.json", "utf8")).match(/uview|secret-extended-key|-----BEGIN|zffrost1|contact-token/i), "Mainnet demo env fixture excludes private material values"],
  [(await readFile("fixtures/mainnet-demo/p0-018-view-only-preflight-pending.json", "utf8")).includes('"status": "WAIT_FUNDING"'), "Mainnet view preflight fixture records funding wait"],
  [(await readFile("fixtures/mainnet-demo/p0-018-view-only-preflight-pending.json", "utf8")).includes('"funded_value_observed": false'), "Mainnet view preflight fixture does not claim funding"],
  [!(await readFile("fixtures/mainnet-demo/p0-018-view-only-preflight-pending.json", "utf8")).match(/uview1|uivk1|secret-extended-key|-----BEGIN|zffrost1/i), "Mainnet view preflight fixture excludes private material values"],
  [(await readFile("fixtures/mainnet-demo/p0-018-view-only-preflight-funded.json", "utf8")).includes('"status": "PASS"'), "Funded mainnet view fixture passes"],
  [(await readFile("fixtures/mainnet-demo/p0-018-view-only-preflight-funded.json", "utf8")).includes('"total_zatoshis": 20000'), "Funded mainnet view fixture records 20000 observed zatoshis"],
  [(await readFile("fixtures/mainnet-demo/p0-018-view-only-preflight-funded.json", "utf8")).includes('"funded_value_observed": true'), "Funded mainnet view fixture records wallet-observed funding"],
  [!(await readFile("fixtures/mainnet-demo/p0-018-view-only-preflight-funded.json", "utf8")).match(/uview1|uivk1|secret-extended-key|-----BEGIN|zffrost1/i), "Funded mainnet view fixture excludes private material values"],
  [p0_018CompatPatch.toString("utf8").includes("is_pre_ironwood_server"), "P0-018 records the pre-Ironwood server compatibility patch"],
  [p0_018CompatPatchRef === P0_018_COMPAT_PATCH_REF, "P0-018 compatibility patch fingerprint matches"],
  [(await readFile("scripts/mainnet-view.mjs", "utf8")).includes(P0_018_COMPAT_PATCH_REF), "Mainnet view CLI pins the P0-018 compatibility patch fingerprint"],
  [(await readFile("src/fixed-runner-v1.mjs", "utf8")).includes('"proof.generate": operationProofGenerate'), "Fixed runner implements proof generation"],
  [(await readFile("src/fixed-runner-v1.mjs", "utf8")).includes('"proof.verify": operationProofVerify'), "Fixed runner implements proof verification"],
  [(await readFile("docs/proof/zecsafe-proof-v1.schema.json", "utf8")).includes('"zecsafe-proof-v1"'), "Proof JSON schema exists"],
  [(await readFile("PROOF_SPEC.md", "utf8")).includes("bundle_hash"), "Proof spec documents bundle hash"],

  // R-09. Internal operating context stays out of the public judge path.
  [await exists("docs/history/HANDOFF.md"), "HANDOFF is retained as historical evidence under docs/history/"],
  [!(await exists("HANDOFF.md")), "HANDOFF is not at the public top level"],
  [!(await exists("docs/operator-notepad.md")), "operator notepad is not on the primary docs path"],
  [!/\/home\/[a-z]+|C:\\\\Users/.test(await readFile("docs/history/HANDOFF.md", "utf8")), "HANDOFF contains no absolute local machine paths"],
  [await exists("docs/history/README.md"), "history directory has an index"],
  [!(await exists("docs/screenshots/vault-dashboard.png")) && !(await exists("docs/screenshots/recovery-flow.png")), "stale prototype screenshots are removed"],
  [(await readFile(".github/workflows/verify.yml", "utf8")).includes("node-version: [20, 24]"), "CI tests the documented Node range"],
  [(await readFile(".github/workflows/verify.yml", "utf8")).includes("make judge-proof-mainnet-tamper"), "CI runs the mainnet judge and tamper targets"],
  [readme.includes("27d0e850202f3f2c37b7de0ded80bdaac1f9fef1fc663c7d6cf107fad55e8527"), "README states the verified mainnet txid"],
  [readme.includes("make judge-proof-mainnet"), "README states the one-command judge verifier"],
  [readme.includes("https://zecsafe.vercel.app/demo"), "README links the production demo"],
  [readme.includes("Lose one key. Not your ZEC."), "README carries the memory hook"],
  [!readme.includes("does not broadcast"), "README no longer claims ZecSafe cannot broadcast"],
  [!readme.includes("Prepare a production path"), "README no longer defers FROST signing to the future"],
  [!readme.match(/\| Guardian approval acknowledgement/), "README no longer presents browser approvals as a feature"],
  [readme.includes("DKG"), "README states the real group setup mode"],
  [(await readFile("README.md", "utf8")).includes("docs/threat-model.md"), "README links threat model"],
  [(await readFile("docs/frost-windows-setup.md", "utf8")).includes("Visual Studio C++ Build Tools"), "FROST Windows setup includes MSVC requirement"],
  [(await readFile("SUBMISSION.md", "utf8")).includes("## 12. Known limitations"), "submission file follows W5 required structure"],
  [(await readFile("SUBMISSION.md", "utf8")).includes("https://zecsafe.vercel.app/demo"), "submission file links the production demo"],
  [(await readFile("docs/architecture-diagram.md", "utf8")).includes("flowchart TD"), "architecture diagram includes Mermaid"],
  [(await readFile("docs/demo-script.md", "utf8")).includes("Target length"), "demo script exists"],
  [(await readFile("docs/threat-model.md", "utf8")).includes("Sensitive Data Rules"), "threat model includes sensitive data rules"],
  [styles.includes("@media (max-width: 680px)"), "styles.css includes mobile breakpoint"],
];

const failures = checks.filter(([passed]) => !passed);

if (failures.length > 0) {
  for (const [, message] of failures) {
    console.error(`Missing check: ${message}`);
  }
  process.exit(1);
}

console.log("ZecSafe static verification passed.");
